### ISSUE TITLE
Enhance Input Validation for snake-function

### ISSUE THREAD

**Issue by sasibhumaraju** [sasibhumaraju/snake-function#1]
# Description:

Currently, the snake-function package only converts strings to snake_case, but it doesn’t validate the input before processing. This could lead to issues if non-string values are passed in.

# Task:

- Add input validation to ensure only strings are processed.
- If a non-string value (e.g., number, object, array) is passed, throw an error or return a default message (e.g., "Invalid input: please provide a string").
- Update the README to reflect this new feature and provide examples.
# Recommended Steps:

- Check if the input is a string.
- If not, return an error or a default message.
- Write a unit test to verify the behavior.
- Update the README with the new validation feature.

**Comment by Saichandra2520** [comment]
Hello @sasibhumaraju I will work on this.
